api/urls.py
from re import I
from django.urls import path
from . import views 

app_name = 'api'

urlpatterns = [
    path('all-questions', views.QuestionList.as_view(), name='all-questions'),
]

learn/urls.py
from django.urls import path
from . import views

# ChapterList
# ChapterDetail
# EditChapter
# PageDetail
# get_question_list
# add_question
# edit_question
# delete_question


app_name = "learn"

urlpatterns = [
    path("chapters", views.ChapterList.as_view(), name="chapter-list"),
    path("chapter/<int:pk>", views.ChapterDetail.as_view(), name="chapter-detail"),
    path(
        "chapter/<int:chapter_pk>/page/<int:page_no>",
        views.PageDetail.as_view(),
        name="page-detail",
    ),
    path("edit-chapter/<int:pk>", views.EditChapter.as_view(), name="edit-chapter"),
    path("question-list", views.get_question_list, name="question-list"),
    path("add-question", views.add_question, name="add-question"),
    path("edit-question/<int:pk>/", views.edit_question, name="edit-question"),
    path("delete-question/<int:pk>/", views.delete_question, name="delete-question"),
    path("toggle-bookmark/<int:pk>/", views.toggle_bookmark, name="toggle-bookmark"),
    path("toggle-completion", views.toggle_completion, name="toggle-completion"),
    path("scoll-height", views.scroll_height, name="scroll-height"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('learn/', include('learn.urls')),
    path('practice/', include('practice.urls')),
    path('api/', include('api.urls')),
]

learn/models.py
from django.db import models
from django.urls import reverse

class Chapter(models.Model):
    title = models.CharField(max_length=100)
    slno = models.IntegerField(default=0)
    no_of_pages = models.IntegerField(default=0)
    scroll_height = models.FloatField(default=0.0)
    
    class Meta:
        ordering = ['slno']
        
    def get_absolute_url(self):
        return reverse("learn:chapter-detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return f"{self.title} ({self.no_of_pages})"

class Question(models.Model):
    rule = models.CharField(max_length=1000, default='')
    question = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)

    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    page_no = models.IntegerField()

    is_bookmarked = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.question} | {self.chapter.title} ({self.corresponding_page_no})"


class PageComplition(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    page_number = models.IntegerField()

    def __str__(self):
        return f"{self.chapter.title} page {self.page_number} completed."

learn/views.py
from django import urls
from django.db.models import query_utils
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, ListView, DeleteView, TemplateView
from .models import Chapter, Question, PageComplition
from django.http import JsonResponse 
from django.contrib import messages
import json

class ChapterList(ListView):
    model = Chapter 

class ChapterDetail(DetailView):
    model = Chapter 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        chapter = get_object_or_404(Chapter, pk=self.kwargs['pk'])
        context["question_list"] = Question.objects.filter(chapter=chapter)
        # context["page_url_list"] = [f"https://raw.githubusercontent.com/my-personal-repos/english-grammar-book/main/chapter-{chapter.slno}/{page}.jpg" for page in range(1, chapter.no_of_pages + 1)]
        context["page_number_list"] = [(page_number, chapter.pk) for page_number in range(1, chapter.no_of_pages + 1)]
        return context
    
class EditChapter(UpdateView):
    model = Chapter 
    fields = "__all__"

class PageDetail(TemplateView):
    template_name = 'learn/page_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["chapter_pk"] = self.kwargs['chapter_pk']
        context["page_no"] = self.kwargs['page_no']
        chapter = get_object_or_404(Chapter, pk=self.kwargs['chapter_pk'])
        page_complition = PageComplition.objects.filter(chapter=chapter, page_number=self.kwargs['page_no']).first()
        if page_complition:
            context["is_completed"] = True
        else:
            context["is_completed"] = False
        if chapter.no_of_pages == self.kwargs['page_no']:
            next_page = 1
        else:
            next_page = int(self.kwargs['page_no']) + 1

        if self.kwargs['page_no'] == 1:
            prev_page = chapter.no_of_pages
        else:
            prev_page = int(self.kwargs['page_no']) - 1
        context["next_page"] = next_page
        context["prev_page"] = prev_page
        context["chapter"] = chapter
        context["question_list"] = Question.objects.filter(chapter=chapter, page_no=self.kwargs['page_no']).order_by('-pk')
        return context
    
def get_question_list(request, chapter_pk, page_no):
    chapter = get_object_or_404(Chapter, pk=chapter_pk)
    question_list = Question.objects.filter(chapter=chapter, page_no=page_no)
    return JsonResponse({"question_list": json.dumps(question_list)})


def add_question(request):
    if request.method == 'POST':
        rule = request.POST.get('rule').strip()
        question = request.POST.get('question').strip()
        answer = request.POST.get('answer').strip()
        chapter_pk = request.POST.get('chapter_pk')
        page_no = request.POST.get('page_no')

        chapter = Chapter.objects.filter(pk=chapter_pk).first()
        if chapter and chapter.no_of_pages>int(page_no):
            if len(question) > 0 and len(answer) > 0:
                Question.objects.create(question=question, answer=answer, rule=rule, chapter=chapter, page_no=page_no)
                messages.success(request, 'Question added successfully')
                return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))
            else:
                messages.error(request, 'Some error occoured')
                return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))
        else:
            messages.error(request, 'Some error occoured')
            return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))    
    else:
        return render(request, "403.html", status=403)


def edit_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        rule = request.POST.get('rule').strip()
        question = request.POST.get('question').strip()
        answer = request.POST.get('answer').strip()
        question_pk = request.POST.get('question_pk')

        try:
            question_obj= get_object_or_404(Question, pk=int(question_pk))
            page_no = question_obj.page_no
            chapter_pk = question_obj.chapter.pk
            if len(question) > 0 and len(answer) > 0:
                question_obj.question = question
                question_obj.answer = answer
                question_obj.rule = rule
                question_obj.save()
                messages.success(request, 'Question Edited Successfully')
                return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))
            else:
                messages.success(request, 'Question and Answer both are required')
                return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))
        except:
            messages.success(request, 'Question not found')
            return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))
    else:
        return render(request, "learn/question_form.html", {"question": question})


def delete_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        chapter_pk = question.chapter.pk
        page_no = question.page_no
        question.delete()
        return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))
    else:
        return render(request, "learn/question_confirm_delete.html", {"question": question})


def toggle_bookmark(request, pk):
    question = get_object_or_404(Question, pk=pk)

    question.is_bookmarked = not question.is_bookmarked
    question.save()
    return redirect(reverse('learn:page-detail', args=[question.chapter.pk, question.page_no]))

def toggle_completion(request):
    if request.method == 'POST':
        page_no = request.POST.get('page_no')
        chapter_pk = request.POST.get('chapter_pk')
        chapter = get_object_or_404(Chapter, pk=chapter_pk)
        obj = PageComplition.objects.filter(page_number=page_no, chapter=chapter).first()
        if obj is not None:
            obj.delete()
        else:
            PageComplition.objects.create(chapter=chapter, page_number=page_no)

        return redirect(reverse('learn:page-detail', args=[chapter_pk, page_no]))


def scroll_height(request):
    if request.method == "POST":
        s_height = request.POST.get('s_height')
        c_pk = request.POST.get('c_pk')

        chapter = get_object_or_404(Chapter, pk=int(c_pk))
        chapter.scroll_height = s_height 
        chapter.save()
        return JsonResponse({"status": "true", "message": "height updated"})
    else:
        return HttpResponse("Hi, You are cheating. ;-)")

learn/templates/learn/chapter_detail.html
{% extends 'base.html' %}

{% block page_title %} {{chapter.title}} {% endblock page_title %}


{% block page_content %}

<div class="container">
<h1 class="text-center">{{chapter.title}}</h1>

{% for page_number, chapter_pk in page_number_list %}
    {% comment %} <span class="badge btn btn-primary">Go to page <a href="">{{page_number}}</a></span> {% endcomment %}
    <a href="{% url 'learn:page-detail' chapter_pk page_number %}" class="btn btn-primary mb-3">Go to page {{page_number}}</a>
{% endfor %}

<br>
<a href="{% url 'learn:edit-chapter' chapter.pk %}">Update Chapter</a>
</div>



{% endblock page_content %}




{% block page_script %}{% endblock page_script %}

learn/templates/learn/chapter_form.html
{% extends 'base.html' %}

{% block page_title %} {{chapter.title}} {% endblock page_title %}


{% block page_content %}

<div class="container">
<h1>Update {{form.insance.title}}</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save" class="btn btn-primary">
</form>

</div>

{% endblock page_content %}




{% block page_script %}{% endblock page_script %}

learn/templates/learn/chapter_list.html
{% extends 'base.html' %}

{% block page_title %} All Chapters {% endblock page_title %}


{% block page_content %}

<div class="container">
{% for chapter in chapter_list %}

<h4><a href="{% url 'learn:chapter-detail' chapter.pk %}" class="no-underline">Chapter {{chapter.slno}} : {{chapter.title}}</a></h4>

{% endfor %}
</div>


{% endblock page_content %}




{% block page_script %}{% endblock page_script %}

learn/templates/learn/page_detail.html
{% extends 'base.html' %}

{% block page_title %} {{chapter.title}} - Page {{page_no}} {% endblock page_title %}

{% block page_style %}
<style>
#main-div::-webkit-scrollbar,
#question-sidebar::-webkit-scrollbar{
     width: 0 !important
}
::-webkit-scrollbar{
     width: 0 !important
}
</style>

{% endblock page_style %}

{% block page_content %}

<div class="row" id="main-div">
    <div class="col-lg-8 col-sm-12">
        <img src="https://raw.githubusercontent.com/my-personal-repos/english-grammar-book/main/chapter-{{chapter_pk}}/{{page_no}}.jpg" class="w-100 border" alt="">
    </div>

    <div class="col-lg-4 col-sm-12 sticky-lg-top overflow-auto border-bottom pb-5" id="question-sidebar" style="max-height:85vh;">
        <div class="d-flex justify-content-between">
            <a href="{% url 'learn:page-detail' chapter_pk prev_page %}" class="btn btn-primary d-flex align-items-center">&lt; Prev</a>
            <div class="d-flex flex-column justify-content-center text-center">
                <div>
                    <b><a href="{% url 'learn:chapter-detail' chapter_pk %}">{{chapter.title}}</a></b> 
                </div>
                <div>
                    <span class="lead">Page {{page_no}} of {{chapter.no_of_pages}}</span>
                </div>
            </div>
            <a href="{% url 'learn:page-detail' chapter_pk next_page %}" class="btn btn-primary d-flex align-items-center">Next &gt;</a>
        </div>
        <hr>
        <div class="{% if is_completed == False %} {% else %} d-none {% endif %}">
            <h6>Add Question</h6>
            <form action="{% url 'learn:add-question' %}" id="new-question-form" method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="rule" name="rule" placeholder="Enter Rule" autofocus>
                    <button type="button" class="btn btn-outline-primary" id="copy-btn-1" onclick="copyToClipboard('rule', 'copy-btn-1')"><i class="fa fa-clipboard" aria-hidden="true"></i></button>
                    <button type="button" class="btn btn-outline-primary" id="recording-btn-1" onclick="startDictation('rule', 'recording-btn-1')"><i class="fa fa-microphone" aria-hidden="true"></i></button>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="question" name="question" placeholder="Enter Question">
                    <button type="button" class="btn btn-outline-primary" onclick="insertBlank()">__</button>
                    <button type="button" class="btn btn-outline-primary" id="recording-btn-2" onclick="startDictation('question', 'recording-btn-2')"><i class="fa fa-microphone" aria-hidden="true"></i></button>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="answer" name="answer" placeholder="Enter Answer">
                    <button type="button" class="btn btn-outline-primary" id="recording-btn-3" onclick="startDictation('answer', 'recording-btn-3')"><i class="fa fa-microphone" aria-hidden="true"></i></button>
                </div>
                <!-- {{chapter_pk}}, {{page_no}} -->
                <input type="number" name="chapter_pk" id="chapter_pk" hidden value="{{chapter_pk}}">
                <input type="number" name="page_no" id="page_no" hidden value="{{page_no}}">
                <div class="d-flex flex-row-reverse">
                    <input type="submit" value="Save" class="btn btn-primary btn-sm">
                    <input type="button" value="Clear" onclick="document.querySelector('#new-question-form').reset()" class="btn btn-primary btn-sm mx-1">
                </div>
            </form>
        </div>
        <hr>
        <h6>Questions</h6>
        <div class="mt-1">
        {% for question in question_list %}
        {% include 'learn/includes/accordion-item.html' with counter=forloop.counter question=question %}
        {% empty %}
            <p class="lead">No Question Available till now </p>
        {% endfor %}
        </div>
        <br>
        <div class="d-flex justify-content-between">
            <form action="{% url 'learn:toggle-completion' %}" method="POST" id="completion-form">
                {% csrf_token %}
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" name="is_completed" role="switch" id="page-completed" name="page-completed" {% if is_completed == False %}  {% else %} checked {% endif %}>
                    <input type="hidden" name="chapter_pk" value="{{chapter_pk}}">
                    <input type="hidden" name="page_no" value="{{page_no}}">
                    <label class="form-check-label" for="page-completed">{% if is_completed == False %}Page Not Completed {% else %}Page Completed{% endif %}</label>
                </div>
            </form>
            <div>
                <button type="button" class="btn-blank" data-bs-toggle="modal" data-bs-target="#page-fullscreen"><i class="bi bi-fullscreen"></i></button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="page-fullscreen" tabindex="-1" aria-labelledby="page-fullscreenLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable  modal-xl">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="page-fullscreenLabel"> {{chapter.title}} - Page {{page_no}} </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <img src="https://raw.githubusercontent.com/my-personal-repos/english-grammar-book/main/chapter-{{chapter_pk}}/{{page_no}}.jpg" class="w-100" alt="">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
</div>

{% endblock page_content %}




{% block page_script %}

<script>

window.onload = ()=>{
    document.documentElement.scrollTop = parseFloat('{{chapter.scroll_height}}')
}

let switchBtn = document.querySelector('#page-completed')
let form = document.querySelector('#completion-form')
switchBtn.addEventListener('click', e=>{
    form.submit()
    console.log('changing')
})

document.addEventListener('scroll', e=>{
    let scrollHeight = document.documentElement.scrollTop
    let dataList = [['s_height', scrollHeight], ['c_pk', '{{chapter.pk}}'], ["csrfmiddlewaretoken", '{{csrf_token}}']]
    post("{% url 'learn:scroll-height' %}", dataList, ()=>{console.log('Height updated')}, ()=>{console.log('Failed to update height. Some error occoured')}, null, null)
})

</script>

<script>
    function insertBlank(){
        let element = document.querySelector('#question')
        element.value = element.value + ' _____ '
        element.focus()
    }
    function copyToClipboard(elementId, buttonId){
        let element = document.querySelector(`#${elementId}`)
        let button = document.querySelector(`#${buttonId}`)
        navigator.clipboard.writeText(element.value)
        button.innerHTML = '<i class="fa fa-check" aria-hidden="true"></i>'
        setTimeout(()=>{
            button.innerHTML = '<i class="fa fa-clipboard" aria-hidden="true"></i>'
        }, 1.5 * 1000)
    }
    function toTitleCase(string){
        return string.trim().toUpperCase().charAt(0) + string.trim().slice(1)
    }
    function startDictation(elementId, buttonId) {

        if (window.hasOwnProperty('webkitSpeechRecognition')) {

            var recognition = new webkitSpeechRecognition();

            recognition.continuous = false;
            recognition.interimResults = false;
            recognition.lang = "en-US";
            recognition.start();
            document.querySelector(`#${buttonId}`).className = 'btn btn-success'
            
            recognition.onresult = function (e) {
                document.querySelector(`#${elementId}`).value = toTitleCase(document.querySelector(`#${elementId}`).value + ' ' + e.results[0][0].transcript)
                recognition.stop();
                document.querySelector(`#${buttonId}`).className = 'btn btn-outline-primary'
                document.querySelector(`#${elementId}`)
            };
            recognition.onerror = function (e) {
                recognition.stop();
                document.querySelector(`#${buttonId}`).className = 'btn btn-danger'
            }
        }
    }
</script>

{% endblock page_script %}

learn/templates/learn/question_confirm_delete.html
{% extends 'base.html' %}


{% block page_title %}Confirm Delete Question{% endblock page_title %}


{% block page_content %}
<div class="container">
    <h1>Confirm Delete Question?</h1>
    <p class="lead">Question: {{question.question}}</p>
    <p class="lead">Answer: {{question.answer}}</p>
    <p class="lead">Rule: {{question.rule}}</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
        <a href="{% url 'learn:page-detail' question.chapter.pk question.page_no %}" class="btn btn-primary">Cancel</a>
        <a href="{% url 'learn:edit-question' question.pk %}" class="btn btn-warning">Rather Edit</a>
    </form>

</div>



{% endblock page_content %}

learn/templates/learn/question_form.html
{% extends 'base.html' %}

{% block page_title %}Edit Question of chapter {{question.chapter.title}}{% endblock page_title %}

{% block page_content %}

    <div class="container">
        <h1>Edit Question</h1>
        <form action="{% url 'learn:edit-question' question.pk %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="question" class="form-label">Question</label>
                <input type="text" class="form-control" id="question" name="question" value="{{question.question}}">
            </div>
            <div class="mb-3">
                <label for="answer" class="form-label">Answer</label>
                <input type="text" class="form-control" id="answer" name="answer" value="{{question.answer}}">
            </div>
            <div class="mb-3">
                <label for="rule" class="form-label">Rule</label>
                <input type="text" class="form-control" id="rule" name="rule" value="{{question.rule}}">
            </div>
            <input type="hidden" name="question_pk" value="{{question.pk}}">
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>

{% endblock page_content %}