api/urls.py
from re import I
from django.urls import path
from . import views 

app_name = 'api'

urlpatterns = [
    path('all-questions', views.QuestionList.as_view(), name='all-questions'),
]

learn/urls.py
from django.urls import path
from . import views

# ChapterList
# ChapterDetail
# EditChapter
# PageDetail
# get_question_list
# add_question
# edit_question
# delete_question


app_name = "learn"

urlpatterns = [
    path("chapters", views.ChapterList.as_view(), name="chapter-list"),
    path("chapter/<int:pk>", views.ChapterDetail.as_view(), name="chapter-detail"),
    path(
        "chapter/<int:chapter_pk>/page/<int:page_no>",
        views.PageDetail.as_view(),
        name="page-detail",
    ),
    path("edit-chapter/<int:pk>", views.EditChapter.as_view(), name="edit-chapter"),
    path("question-list", views.get_question_list, name="question-list"),
    path("add-question", views.add_question, name="add-question"),
    path("edit-question/<int:pk>/", views.edit_question, name="edit-question"),
    path("delete-question/<int:pk>/", views.delete_question, name="delete-question"),
    path("toggle-bookmark/<int:pk>/", views.toggle_bookmark, name="toggle-bookmark"),
    path("toggle-completion", views.toggle_completion, name="toggle-completion"),
    path("scoll-height", views.scroll_height, name="scroll-height"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('learn/', include('learn.urls')),
    path('practice/', include('practice.urls')),
    path('api/', include('api.urls')),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/1994/1994339.png" type="image/png">
    <!-- Fontawesome Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Bootstrap Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block page_style %}{% endblock page_style %}
    <style>
    .no-underline{
        text-decoration: none;
    }
    .btn-blank{
        cursor: pointer;
        background-color: transparent;
        border: none;
        outline: none;
        
    }
    #parent-div::-webkit-scrollbar{
        width: 0 !important
    }
    .slide-in{
        position: absolute;
        top: 0;
        animation: slowlyfade 2s 1;
        animation-delay: 3s;
        margin-top: 75px;
        animation-fill-mode: forwards;
    }
    @keyframes slowlyfade {
        from {
            opacity: 1;
        }
        to{
            opacity: 0;
        }
    }

    </style>
    <title>{% block page_title %}{% endblock page_title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">English Grammar</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'learn:chapter-list' %}">Chapters</a>
                </li>
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'api:all-questions' %}">Api</a>
                </li>  {% endcomment %}
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            </div>
        </div>
    </nav>
    <div class="container-fluid my-3">
        {% if messages %}
            {% for message in messages %}
            <div class="w-25 alert slide-in alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
                {{message}}
                {% comment %} <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> {% endcomment %}
            </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="container-fluid mb-5" id="parent-div">
        {% block page_content %}{% endblock page_content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Axios CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
    <script>
        function post(url, dataList, onSuccess, onFail, onSArgs, onFArgs){
            let data = new FormData();

            dataList.forEach(dataItem => data.append(dataItem[0], dataItem[1]))
            // data.append("csrfmiddlewaretoken", '{{csrf_token}}')
            
            axios.post(url, data)
            .then(res => onSuccess(res, onSArgs))
            .catch(errors => onFail(errors, onFArgs))
        }
    </script>
    {% block page_script %}{% endblock page_script %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block page_title %} English Grammar {% endblock page_title %}


{% block page_content %}

<div class="container">

    <div class="accordion" id="question-accrodion">
        {% for question in question_list %}
            {% include 'learn/includes/accordion-item.html' with counter=forloop.counter question=question %}
        {% empty %}
            <p class="lead">No Question Available till now </p>
        {% endfor %}
    </div>

</div>

{% endblock page_content %}




{% block page_script %}{% endblock page_script %}